In [2]:
import pandas as pd
import ir_datasets

qrels = (
    pd.DataFrame(ir_datasets.load("msmarco-passage/trec-dl-2020/judged").qrels_iter())
    .astype({"query_id": str, "doc_id": str})
    .drop("iteration", axis="columns")
    .assign(relevance=lambda df: (df["relevance"] > 0.5).astype(int))
    .merge(
        pd.read_parquet("../data/processed/trecdl-shallow-qrels-128.parquet")
        .astype({"query_id": str, "doc_id": str})
        .assign(relevance=lambda df: (df["relevance"] > 0.5).astype(int))
        .rename({"relevance": "relevance_adapter_128"}, axis="columns"),
        how = "left",
        on = ["query_id", "doc_id"],
    )
    .merge(
        pd.read_parquet("../data/processed/trecdl-shallow-qrels-64.parquet")
        .astype({"query_id": str, "doc_id": str})
        .assign(relevance=lambda df: (df["relevance"] > 0.5).astype(int))
        .rename({"relevance": "relevance_adapter_64"}, axis="columns"),
        how = "left",
        on = ["query_id", "doc_id"],
    )
    .merge(
        pd.read_parquet("../data/processed/trecdl-shallow-qrels-192.parquet")
        .astype({"query_id": str, "doc_id": str})
        .assign(relevance=lambda df: (df["relevance"] > 0.5).astype(int))
        .rename({"relevance": "relevance_adapter_192"}, axis="columns"),
        how = "left",
        on = ["query_id", "doc_id"],
    )
    .merge(
        pd.read_parquet("../data/processed/trecdl-shallow-qrels-256.parquet")
        .astype({"query_id": str, "doc_id": str})
        .assign(relevance=lambda df: (df["relevance"] > 0.5).astype(int))
        .rename({"relevance": "relevance_adapter_256"}, axis="columns"),
        how = "left",
        on = ["query_id", "doc_id"],
    )
    .merge(
        pd.read_parquet("../data/processed/trecdl-shallow-qrels-256.parquet")
        .astype({"query_id": str, "doc_id": str})
        .assign(relevance=0)
        .rename({"relevance": "relevance_baseline"}, axis="columns"),
        how = "left",
        on = ["query_id", "doc_id"],
    )
    .merge(
        pd.read_parquet("../data/processed/trecdl-llm-qrels.parquet")
        .assign(relevance=lambda df: (df["relevance"] > 0.5).astype(int))
        .query("prompt == 'few_shot_human_8'")
        .drop("prompt", axis="columns")
        .rename({"relevance": "relevance_few_shot_human_8"}, axis="columns"),
        how="left",
        on = ["query_id", "doc_id"],
    )
    .merge(
        pd.read_parquet("../data/processed/trecdl-llm-qrels.parquet")
        .assign(relevance=lambda df: (df["relevance"] > 0.5).astype(int))
        .query("prompt == 'few_shot_umbrela_8'")
        .drop("prompt", axis="columns")
        .rename({"relevance": "relevance_few_shot_umbrela_8"}, axis="columns"),
        how="left",
        on = ["query_id", "doc_id"],
    )
    .merge(
        pd.read_parquet("../data/processed/trecdl-llm-qrels.parquet")
        .assign(relevance=lambda df: (df["relevance"] > 0.5).astype(int))
        .query("prompt == 'umbrela'")
        .drop("prompt", axis="columns")
        .rename({"relevance": "relevance_umbrela"}, axis="columns"),
        how="left",
        on = ["query_id", "doc_id"],
    )
    .merge(
        pd.read_parquet("../data/processed/trecdl-llm-qrels.parquet")
        .assign(relevance=lambda df: (df["relevance"] > 0.5).astype(int))
        .query("prompt == 'human'")
        .drop("prompt", axis="columns")
        .rename({"relevance": "relevance_human_prompt"}, axis="columns"),
        how="left",
        on = ["query_id", "doc_id"],
    )
    .assign(
        relevance_baseline=lambda df: df["relevance_baseline"].where(~df["relevance_adapter_256"].isna(), df["relevance"]),
        relevance_few_shot_human_8=lambda df: df["relevance_few_shot_human_8"].where(~df["relevance_adapter_256"].isna(), df["relevance"]),
        relevance_umbrela=lambda df: df["relevance_umbrela"].where(~df["relevance_adapter_256"].isna(), df["relevance"]),
        relevance_human_prompt=lambda df: df["relevance_human_prompt"].where(~df["relevance_adapter_256"].isna(), df["relevance"]),
        relevance_adapter_64=lambda df: df["relevance_adapter_64"].where(~df["relevance_adapter_256"].isna(), df["relevance"]),
        relevance_adapter_128=lambda df: df["relevance_adapter_128"].where(~df["relevance_adapter_256"].isna(), df["relevance"]),
        relevance_adapter_192=lambda df: df["relevance_adapter_192"].where(~df["relevance_adapter_256"].isna(), df["relevance"]),
        relevance_few_shot_umbrela_8=lambda df: df["relevance_few_shot_umbrela_8"].where(~df["relevance_adapter_256"].isna(), df["relevance"]),
    )
    .assign(
        relevance_adapter_256=lambda df: df["relevance_adapter_256"].where(~df["relevance_adapter_256"].isna(), df["relevance"]),
    )
)

In [3]:
qrels

,query_id,doc_id,relevance,relevance_adapter_128,relevance_adapter_64,relevance_adapter_192,relevance_adapter_256,relevance_baseline,relevance_few_shot_human_8,relevance_few_shot_umbrela_8,relevance_umbrela,relevance_human_prompt
0,23849,1020327,1,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
1,23849,1020327,1,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,23849,1020327,1,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,23849,1020327,1,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
4,23849,1034183,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
15939013,1136962,937258,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
15939014,1136962,937258,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
15939015,1136962,937258,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
15939016,1136962,937258,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
15939017,1136962,999215,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
import krippendorff

df_reliability = []

for c in [
    'relevance_adapter_64',
    'relevance_adapter_128',
    'relevance_adapter_192',
    'relevance_adapter_256',
    'relevance_baseline',
    'relevance_few_shot_umbrela_8',
    'relevance_few_shot_human_8',
    'relevance_human_prompt',
    'relevance_umbrela'
]:
    data = (
        qrels
        .dropna()
        .loc[:, ["relevance", c]]
        .values
        .T
    )
    alpha = krippendorff.alpha(reliability_data=data, level_of_measurement="nominal", value_domain=(0, 1))
    df_reliability.append({
        "qrels": c,
        "alpha": alpha,
    })

df_reliability = pd.DataFrame(df_reliability)
print(df_reliability)

                          qrels     alpha
0          relevance_adapter_64  0.552229
1         relevance_adapter_128  0.488950
2         relevance_adapter_192  0.557203
3         relevance_adapter_256  0.686416
4            relevance_baseline -0.476321
5  relevance_few_shot_umbrela_8  0.489721
6    relevance_few_shot_human_8  0.200417
7        relevance_human_prompt  0.154409
8             relevance_umbrela  0.457146

In [5]:
import trectools
from glob import glob
from tqdm.notebook import tqdm

runs = [trectools.TrecRun(f) for f in glob(f"../data/external/dl20-passages-runs/*.gz")]
depths = [5, 10, 50]
eval_data = []

for c in [
    'relevance_adapter_64',
    'relevance_adapter_128',
    'relevance_adapter_192',
    'relevance_adapter_256',
    'relevance_baseline',
    'relevance_few_shot_umbrela_8',
    'relevance_few_shot_human_8',
    'relevance_human_prompt',
    'relevance_umbrela',
    'relevance'
]:
    jdg = trectools.TrecQrel()
    jdg.qrels_data = (
        qrels
        .dropna()
        .loc[:, ["query_id", "doc_id", c]]
        .rename({"query_id": "query", "doc_id": "docid",c: "rel"}, axis="columns")
    )
    for r in tqdm(runs, desc=c):
        eval = trectools.TrecEval(r, jdg)
        eval_data.append(
            pd.concat([
                pd.concat([eval.get_ndcg(depth=k, per_query=True) for k in depths],
                    axis=1).reset_index().melt(id_vars=["query"]).rename(columns={"variable": "metric"}),
                pd.concat(
                    [eval.get_unjudged(depth=k, per_query=True) for k in depths],
                    axis=1).reset_index().melt(id_vars=["query"]).rename(columns={"variable": "metric"})
            ])
            .reset_index()
            .assign(
                system=r.get_runid(),
                source=c
            )
        )

df = pd.concat(eval_data)

relevance_adapter_64:   0%|          | 0/59 [00:00<?, ?it/s]

relevance_adapter_128:   0%|          | 0/59 [00:00<?, ?it/s]

relevance_adapter_192:   0%|          | 0/59 [00:00<?, ?it/s]

relevance_adapter_256:   0%|          | 0/59 [00:00<?, ?it/s]

relevance_baseline:   0%|          | 0/59 [00:00<?, ?it/s]

relevance_few_shot_umbrela_8:   0%|          | 0/59 [00:00<?, ?it/s]

relevance_few_shot_human_8:   0%|          | 0/59 [00:00<?, ?it/s]

relevance_human_prompt:   0%|          | 0/59 [00:00<?, ?it/s]

relevance_umbrela:   0%|          | 0/59 [00:00<?, ?it/s]

relevance:   0%|          | 0/59 [00:00<?, ?it/s]

In [8]:
(
    df
    .drop(["query", "index"], axis="columns")
    .dropna(subset="value")
    .astype({"value": float, "system": str, "source": str})
    .reset_index(drop=True)
    .groupby(["metric", "system", "source"])
    .mean()
    .reset_index()
    .pivot(index=["system", "metric"], columns="source", values="value")
    .reset_index()
    .set_index("system")
    .groupby("metric")
    .corr(method="spearman")
    .reset_index()
    .query("source == 'relevance'")
    .drop(["source", "relevance"], axis=1)
    .query("metric in ['NDCG@5', 'NDCG@10', 'NDCG@50']")
    .set_index("metric")
    .transpose()
    .loc[:, ['NDCG@5', 'NDCG@10', 'NDCG@50']]
)
##
# relevance_adapter_128,0.869901,0.884337,0.876096
# relevance_adapter_192,0.943133,0.879077,0.899123
# relevance_adapter_256,0.966569,0.954237,0.952425
# relevance_adapter_64,0.843776,0.813676,0.871712
# relevance_baseline,-0.183928,-0.279953,0.521391
# relevance_few_shot_human_8,0.345470,0.206429,0.765985
# relevance_few_shot_umbrela_8,0.803214,0.739100,0.886148
# relevance_human_prompt,0.309468,0.095850,0.741496
# relevance_umbrela,0.632905,0.602513,0.826826

metric                          NDCG@5   NDCG@10   NDCG@50
source
relevance_adapter_128         0.869901  0.884337  0.876096
relevance_adapter_192         0.943133  0.879077  0.899123
relevance_adapter_256         0.966569  0.954237  0.952425
relevance_adapter_64          0.843776  0.813676  0.871712
relevance_baseline           -0.183928 -0.279953  0.521391
relevance_few_shot_human_8    0.345470  0.206429  0.765985
relevance_few_shot_umbrela_8  0.803214  0.739100  0.886148
relevance_human_prompt        0.309468  0.095850  0.741496
relevance_umbrela             0.632905  0.602513  0.826826

In [ ]:
(
    pd.DataFrame()
)